### ISSUE TITLE
Encadré - format OFCE

### ISSUE THREAD

**Issue by madauvin** [OFCE/ofce#13]
Ajout d'un template "encadré" (est ce que cette phrase à un sens?).

Ceci est un pense-bête. je serai râvie de m'auto-assign quand j'aurai le temps de réfléchir à cela (si cela n'a pas déjà été fait)

**Comment by madauvin** [comment]
un point de départ : 

::: { .callout-note }
### Encadré. titre
 La fourmi m'a piquée la main, la coquine la coquine 
la fourmi, m'a piquée la main, la coquine elle avait faim
:::

**Comment by xtimbeau** [comment]
le point d'arrivée

````

::: {#tip-un_label_pour_crossref .callout-tip collapse="true"}
## le titre de l'encadré
La fourmi m'a piquée la main, la coquine la coquine
la fourmi, m'a piquée la main, la coquine elle avait faim
:::
````
