### ISSUE TITLE
numérotation façon US

### ISSUE THREAD

**Issue by hperivier** [OFCE/ofce#16]
Hello la team 
je n'arrive pas à activer l'option numérotation façon US avec la virgule pour les 1000 
j'ai ajouté dans le Yaml : (ça tourne mais me laisse les chiffres façon EU) 
que dois je faire? 
merci! 

format:
  wp-html: 
    number-separator: ","
    number-decimal: "."
  wp-pdf: 
    number-separator: ","
    number-decimal: "."

**Comment by xtimbeau** [comment]
c'est spécifique à chaque tableau/graphique
par exemple dans ggplot
scale_y_number( labels = scales::label_number(decimal.mark = ",")

Dans gt : 
fmt_number(decimal.mark = ",")
