### ISSUE TITLE
Pb chargement package ofce pour certains

### ISSUE THREAD

**Issue by PaulMalliet** [OFCE/ofce#6]
message d'erreur: 
Erreur : Failed to install 'unknown package' from GitHub:
HTTP error 403.
API rate limit exceeded for 193.54.67.93. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

Rate limit remaining: 0/60
Rate limit reset at: 2022-03-23 16:26:27 UTC

To increase your GitHub API rate limit

Use usethis::create_github_token() to create a Personal Access Token.
Use usethis::edit_r_environ() and add the token as GITHUB_PAT.

**Comment by xtimbeau** [comment]
Use usethis::create_github_token() to create a Personal Access Token.
Use usethis::edit_r_environ() and add the token as GITHUB_PAT.
